/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Cocoa Font
 #	author : miyako
 #	12/04/26
 #
 # --------------------------------------------------------------------------------*/



// --- Font List
void FONT_GET_FAMILY_NAMES(sLONG_PTR *pResult, PackagePtr pParams);
void FONT_GET_NAMES(sLONG_PTR *pResult, PackagePtr pParams);
void FONT_GET_FAMILY_MEMBER_NAMES(sLONG_PTR *pResult, PackagePtr pParams);
void FONT_GET_DISPLAY_NAMES(sLONG_PTR *pResult, PackagePtr pParams);

// --- Font Traits
void FONT_GET_INFORMATION(sLONG_PTR *pResult, PackagePtr pParams);
void FONT_Get_traits(sLONG_PTR *pResult, PackagePtr pParams);
void FONT_Get_weight(sLONG_PTR *pResult, PackagePtr pParams);

// --- Localization
void FONT_Get_display_name(sLONG_PTR *pResult, PackagePtr pParams);
void FONT_Get_localized_name(sLONG_PTR *pResult, PackagePtr pParams);
